x-env-file: &default-env
   default.env

x-logging: &default-logging
  options:
    max-size: "10M"
    max-file: "2"

x-logging-loki: &loki-logging
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
      mode: "non-blocking"
      max-buffer-size: "10M"
      loki-retries: 5
      max-size: "10M"
      max-file: "2"


services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: always
    command:
      - -config.file=/etc/loki/loki-config.yml
    volumes:
      - loki-data:/loki
      - ./config/loki/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - redis-net
    <<: *loki-logging


  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=10d'
      - '--log.level=warn'
    networks:
      - redis-net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
      - loki
    networks:
      - redis-net
    logging: *default-logging

  # Databases / message queues

  redis-primary:
    container_name: redis-primary
    build:
      context: ./containers/redis/
      dockerfile: Dockerfile
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]
    volumes:
      - redis-primary-data:/data
    networks:
      redis-net:
        ipv4_address: 172.28.0.10
    logging: *default-logging

  redis-replica-1:
    container_name: redis-replica-1
    build:
      context: ./containers/redis/
      dockerfile: Dockerfile
    restart: always
    command: ["redis-server", "--replicaof", "172.28.0.10", "6379", "--protected-mode", "no"]
    depends_on:
      - redis-primary
    volumes:
      - redis-replica-1-data:/data
    networks:
      redis-net:
        ipv4_address: 172.28.0.11
    logging: *default-logging

  redis-replica-2:
    container_name: redis-replica-2
    build:
      context: ./containers/redis/
      dockerfile: Dockerfile
    restart: always
    command: ["redis-server", "--replicaof", "172.28.0.10", "6379", "--protected-mode", "no"]
    depends_on:
      - redis-primary
    volumes:
      - redis-replica-2-data:/data
    networks:
      redis-net:
        ipv4_address: 172.28.0.12
    logging: *default-logging

  redis-sentinel-1:
    container_name: redis-sentinel-1
    build:
      context: ./containers/redis-sentinel/
      dockerfile: Dockerfile
    restart: always
    command: ["redis-sentinel","/usr/local/etc/redis/sentinel.conf"]
    ports:
      - "26379:26379"
    depends_on:
      - redis-primary
      - redis-replica-1
      - redis-replica-2
    networks:
      redis-net:
        ipv4_address: 172.28.0.20
    logging: *default-logging

  redis-sentinel-2:
    container_name: redis-sentinel-2
    build:
      context: ./containers/redis-sentinel/
      dockerfile: Dockerfile
    restart: always
    command: ["redis-sentinel","/usr/local/etc/redis/sentinel.conf"]
    ports:
      - "26380:26379"
    depends_on:
      - redis-primary
      - redis-replica-1
      - redis-replica-2
    networks:
      redis-net:
        ipv4_address: 172.28.0.21
    logging: *default-logging

  redis-sentinel-3:
    container_name: redis-sentinel-3
    build:
      context: ./containers/redis-sentinel/
      dockerfile: Dockerfile
    restart: always
    command: ["redis-sentinel","/usr/local/etc/redis/sentinel.conf"]
    ports:
      - "26381:26379"
    depends_on:
      - redis-primary
      - redis-replica-1
      - redis-replica-2
    networks:
      redis-net:
        ipv4_address: 172.28.0.22
    logging: *default-logging

  # Task handling
  celery:
    restart: always
    build:
      context: .
      dockerfile: ./containers/celery/Dockerfile
    volumes:
      - "./downloads/:/data"
      - "./:/local"
      - "prometheus-metrics-data:/tmp/prometheus_metrics"
    env_file: *default-env
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_metrics
    tty: true
    depends_on:
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
      - subscription-manager
    networks:
      - redis-net
    logging: *default-logging

  # Main application
  subscription-manager:
    container_name: subscription-manager
    restart: always
    build:
      context: .
      dockerfile: ./containers/subscription_manager/Dockerfile
    ports:
      - "5002:5001"
    volumes:
      - "./downloads/:/data"
      - "./:/local/app"
      - "./config/subscription_manager/:/app/config/"
      - "prometheus-metrics-data:/tmp/prometheus_metrics"
    env_file: *default-env
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_metrics
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
    tty: true
    depends_on:
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
    networks:
      - redis-net
    logging: *default-logging


  subscriber-france:
    container_name: subscriber
    restart: always
    build:
      context: .
      dockerfile: ./containers/subscriber/Dockerfile
    env_file: *default-env
    environment:
      GLOBAL_BROKER_HOST: globalbroker.meteo.fr
      GLOBAL_BROKER_PORT: 443
      GLOBAL_BROKER_USERNAME: everyone
      GLOBAL_BROKER_PASSWORD: everyone
      MQTT_PROTOCOL: websockets
    depends_on:
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
    networks:
      - redis-net
    logging: *default-logging


volumes:
  loki-data:
  prometheus-data:
  prometheus-metrics-data:
  grafana-data:
  redis-primary-data:
  redis-replica-1-data:
  redis-replica-2-data:

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16