x-env-file: &default-env
   default.env

x-logging: &default-logging
  options:
    max-size: "10M"
    max-file: "2"

x-logging-loki: &loki-logging
  driver: loki
  options:
    loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
    loki-retries: "5"
    mode: "non-blocking"
    max-buffer-size: "4m"
    keep-file: "true"
    max-size: "10m"
    max-file: "3"


services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    restart: always
    command:
      - -config.file=/etc/loki/loki-config.yml
    volumes:
      - loki-data:/loki
      - ./config/loki/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - redis-net
    logging: *default-logging


  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=10d'
      - '--log.level=warn'
    networks:
      - redis-net
    logging: *loki-logging

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - prometheus
      - loki
    networks:
      - redis-net
    logging: *loki-logging

  # Databases / message queues

  redis:
    container_name: redis
    build:
      context: ./containers/redis/
      dockerfile: Dockerfile
    restart: always
    env_file: *default-env
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    logging: *loki-logging
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Task handling
  celery:
    restart: always
    build:
      context: .
      dockerfile: ./containers/celery/Dockerfile
    volumes:
      - "./downloads/:/data"
      - "./:/local"
    env_file: *default-env
    tty: true
    depends_on:
      - redis
      - subscription-manager
    networks:
      - redis-net
    logging: *loki-logging
    healthcheck:
      test: [ "CMD", "celery", "inspect", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3

  # Main application
  subscription-manager:
    container_name: subscription-manager
    restart: always
    build:
      context: .
      dockerfile: ./containers/subscription_manager/Dockerfile
    ports:
      - "5002:5001"
    volumes:
      - "./downloads/:/data"
      - "./:/local/app"
      - "./config/subscription_manager/:/app/config/"
    env_file: *default-env
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
    tty: true
    depends_on:
      - redis
    networks:
      - redis-net
    logging: *loki-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3

  wis2downloader-ui:
      build:
        no_cache: true
        context: .
        dockerfile: ./containers/ui/Dockerfile
      env_file: *default-env
      ports:
        - 8080:8080
      volumes:
        - ./modules/ui:/app # mounting local app directory
      networks:
      - redis-net

  subscriber-france:
    container_name: subscriber-france
    restart: always
    build:
      context: .
      dockerfile: ./containers/subscriber/Dockerfile
    env_file: *default-env
    environment:
      GLOBAL_BROKER_HOST: globalbroker.meteo.fr
      GLOBAL_BROKER_PORT: 443
      GLOBAL_BROKER_USERNAME: everyone
      GLOBAL_BROKER_PASSWORD: everyone
      MQTT_PROTOCOL: websockets
    depends_on:
      - redis
    networks:
      - redis-net
    logging: *loki-logging
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli -a $REDIS_PASSWORD EXISTS subscriber:health:globalbroker-meteo-fr | grep 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

  subscriber-brazil:
    container_name: subscriber-brazil
    restart: always
    build:
      context: .
      dockerfile: ./containers/subscriber/Dockerfile
    env_file: *default-env
    environment:
      GLOBAL_BROKER_HOST: globalbroker.inmet.gov.br
      GLOBAL_BROKER_PORT: 443
      GLOBAL_BROKER_USERNAME: everyone
      GLOBAL_BROKER_PASSWORD: everyone
      MQTT_PROTOCOL: websockets
    depends_on:
      - redis
    networks:
      - redis-net
    logging: *loki-logging
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli -a $REDIS_PASSWORD EXISTS subscriber:health:globalbroker-inmet-gov-br | grep 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  loki-data:
  prometheus-data:
  grafana-data:
  redis-data:

networks:
  redis-net:
    driver: bridge
